// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file uxrce_app.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _UXRCE_TRANSPORT_UART_H_
#define _UXRCE_TRANSPORT_UART_H_

#ifdef __cplusplus
extern "C"  
{
#endif // ifdef __cplusplus

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "stm32f4xx_hal.h"
#include <uxr/client/profile/transport/custom/custom_transport.h>

/*!
 * @brief This struct represents the structure HelloWorld defined by the user in the IDL file.
 * @ingroup HELLOWORLD
 */
// 串口类型定义  Definition of UART transport arguments
typedef struct {
    UART_HandleTypeDef *huart;
} uxrUartTransArgs_t;

// 回调函数声明  Callback function declarations
void uxrDds_UartRxCallback(uint8_t *data, uint16_t len);

// open close read write 函数声明  Function declarations for open, close, read, and write
bool uxrDds_UartOpen(uxrCustomTransport *transport);
bool uxrDds_UartClose(uxrCustomTransport *transport);

size_t uxrDds_UartWrite(
    uxrCustomTransport *transport,
    const uint8_t *buffer,
    size_t length,
    uint8_t *error_code);


size_t uxrDds_UartRead (
    uxrCustomTransport* transport,
    uint8_t* buffer,
    size_t length,
    int timeout,
    uint8_t* error_code);

#ifdef __cplusplus
}
#endif // ifdef __cplusplus

#endif // _uxrce_app_H_
